BEGIN;

DROP TABLE IF EXISTS users CASCADE;


CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    name VARCHAR(250)  NOT NULL,
    email VARCHAR(250)  NOT NULL,
    password VARCHAR(250) NOT NULL ,
    phone INTEGER ,
    created_at TEXT DEFAULT TO_CHAR(CURRENT_TIMESTAMP, 'DD/MM/YYYY HH12:MI:SS:MS:US AM')
);

COMMIT;
